adding in internal proxy server

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,6 +22,21 @@ jobs:
         run: |
           sed -i 's|<head>|<head>\n<script>window.HOST_IP="${{ secrets.HOST_IP }}";</script>|' ./public/index.html
 
+      - name: Write SSL certificates to files
+        run: |
+          mkdir -p certs
+          echo "${{ secrets.SSL_CERT }}" > certs/server.crt
+          echo "${{ secrets.SSL_KEY }}" > certs/server.key
+
+      - name: Verify SSL Certificates
+        run: |
+          echo "🔍 Checking SSL certificate files..."
+          if [ ! -s /home/ubuntu/certs/server.crt ] || [ ! -s /home/ubuntu/certs/server.key ]; then
+            echo "❌ Error: SSL certificate files are missing or empty!"
+            exit 1
+          fi
+          ls -la /home/ubuntu/certs/
+
       - name: Set Environment Variable for Docker
         run: echo "HOST_IP=${{ secrets.HOST_IP }}" >> $GITHUB_ENV
 
